/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as PolicyImport } from "./routes/policy";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const PolicyRoute = PolicyImport.update({
   path: "/policy",
   getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
   path: "/",
   getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
   interface FileRoutesByPath {
      "/": {
         id: "/";
         path: "/";
         fullPath: "/";
         preLoaderRoute: typeof IndexImport;
         parentRoute: typeof rootRoute;
      };
      "/policy": {
         id: "/policy";
         path: "/policy";
         fullPath: "/policy";
         preLoaderRoute: typeof PolicyImport;
         parentRoute: typeof rootRoute;
      };
   }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, PolicyRoute });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/policy"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/policy": {
      "filePath": "policy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
